### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Irostovsky** [JJMUSA/django_test#2]
Hello @JJMUSA 
I m Ivan, from GuestReady. Thanks for the doing the test task.

The code looks clean and it works.
I see 1 major red flag:
During the iteration of the reservations into the template, the extra SQL queries happened to get the rental and previous reservation for each reservation. If the count of reservations is N then a totally 2N + 1 SQL requests are done. Could you improve the code please?

**Comment by JJMUSA** [comment]
Hi @Irostovsky 
Thank you for the feedback. I have amended the code to combine the querying for reservation, rental name and previous preservation all into one query can you please take a look to see if that improves the performance.

**Comment by Irostovsky** [comment]
Thanks, @JJMUSA 
The code looks reasonable.
What is about tests?

**Comment by JJMUSA** [comment]
The tests are the under the test folder in django-test.

**Comment by JJMUSA** [comment]
Maybe I misunderstood you question. The tests folder contain the testcases, I have however forgotten to include a test for the view. I will do that now , please.

**Comment by JJMUSA** [comment]
Hi @Irostovsky 
I have updated the repo with the test for the reservation list view. Please see under django_test/tests/test_views,py

**Comment by Irostovsky** [comment]
Thanks, @JJMUSA
